### ISSUE TITLE
Suggestion: change filter keys from name to type_name

### ISSUE THREAD

**Issue by cweinberger** [ryangrimm/VaporElasticsearch#11]
I would suggest to change the composition of the `key` for filters/tokenizers/analyzers in the `Analysis` section:

Currently you only take the `name` of a `filter`. This results into key names like `danish` for the `StemmerFilter` which has potential to conflict in future.

My initial thought would be to use `\(type)_\(name)` for the `key`, ie. `stemmer_danish`, `synonym_foobar`,... What do you think?

@ryangrimm

**Comment by ryangrimm** [comment]
Different filters have different ways that they use the name property. For builtin filters that have no customization options (eg: the standard filter) the name is really quite pointless as you can't create a custom filter in the analysis section of type "standard". Therefore filters of this type can't have a name but since I made the name property required for all filters I simply populate it with the type's raw value.

However, filters that do allow customization (eg: lowercase filter) have two init methods, one without any arguments (which makes it use the builtin lowercase filter) and one that takes a name and a language. In other words, in order for the filter to show up under the analysis.filter section, a name should be provided by the user.

So in the case of your `StemmerFilter`, I'd change your init method to take both a name and a StemmerLanguage. That would allow the user to give it a more descriptive name and have it follow the same pattern as the rest of the filters. Perhaps the name in this case should be optional and have a default value of `(type)_(language.rawValue)`?

**Comment by cweinberger** [comment]
Hi Ryan,

Thanks! How can I specify the name for the filter separately from its name field (that is used for the filter to determine the language)?

Best
Christian

**Comment by ryangrimm** [comment]
Ha! I see your dilemma! The challenge you've got is that the actual key used in the Elasticsearch mapping is called name!

So in that case, I think I'd add another property to hold the language that was passed in by the user. Then I think you should be able to provide some CodingKeys to do the right mapping:

```
enum CodingKeys: String, CodingKey {
    case type
    case language = "name"
}
```

That should do it for the encoding. The decoding will have to be done manually to properly populate the language property. If the Language struct was a flat enum with all the various languages directly in it you could get away with not writing a custom decoder as well.

**Comment by cweinberger** [comment]
Sounds reasonable! Thanks for your input, Ryan!
